export const data = [
  {
    heading: "Clothing Styles",
    subheading: "Explore the Latest Fashion Trends",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Clothing Styles.",
    features: ["Premium Quality", "Limited Edition", "Free Shipping"],
    buttonText: "Shop Now",
    buttonLink: "/category/menClothing  ",
    illustration: "/images/clothing-illustration.png",
  },
  {
    heading: "Electronics Collection",
    subheading: "Discover the New Collection",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Electronics Collection.",
    features: ["Unique Designs", "Exclusive Styles", "Global Inspiration"],
    buttonText: "Explore",
    buttonLink: "/category/electronics",
    illustration: "/images/electronics-illustration.png",
  },
  {
    heading: "Home Interiors",
    subheading: "Experience Luxury",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Home Interiors.",
    features: ["Luxurious Designs", "Handcrafted Details", "Express Delivery"],
    buttonText: "Discover",
    buttonLink: "/category/homeInterior",
    illustration: "/images/home-interiors-illustration.png",
  },
  {
    heading: "Machinery Tools",
    subheading: "Unleash Your Style",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Machinery Tools.",
    features: ["Trendsetting Styles", "Personalized Picks", "Global Influence"],
    buttonText: "Learn More",
    buttonLink: "/category/machineryTools",
    illustration: "/images/machinery-tools-illustration.png",
  },
  {
    heading: "Smartphones Collection",
    subheading: "Elevate Your Wardrobe",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Smartphones Collection.",
    features: ["Versatile Choices", "Seasonal Collections", "Easy Returns"],
    buttonText: "Buy Now",
    buttonLink: "/category/smartphones",
    illustration: "/images/smartphones-illustration.png",
  },
];
